{
 "title": "MyFitnessPal Grafana",
 "time": { "from": "now/w", "to": "now" },
 "panels": [
  { "title": "Monthly Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Calories Consumed ⚡",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kcal" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  calories\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Carbohydrates 🍞",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  carbohydrates\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Fat 🧀",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  fat\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Sodium 🧂",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  sodium\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Protein 🍖",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  protein\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total Sugar 🍬",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  sugar\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  { "title": "Daily Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Average Calories Consumed ⚡",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kcal" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  calories\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Carbohydrates 🍞",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  carbohydrates\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Fat 🧀",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  fat\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Sodium 🧂",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  sodium\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Protein 🍖",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  protein\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Average Sugar 🍬",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "massg" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  sugar\nFROM meals\nWHERE\n  $__timeFilter(date)\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Calories Consumed ⚡",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none", "label": "Calories (kcal)" }
   ],
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT\n  date AS \"time\",\n  sum(calories) AS \"calories\"\nFROM meals\nWHERE\n  $__timeFilter(date)\nGROUP BY date\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Meals 🍽️",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT\n  max(date) as \"time\",\n  food,\n  count(food)\nFROM meals\nWHERE\n  $__timeFilter(date)\nGROUP BY food\norder by count(food) desc"
    }
   ]
  },
  {
   "title": "Average Calories Consumed by Day ⚡",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "kcal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "delimiter": ",",
     "rawSql": "SELECT \n      avg(x.calories) as \"calories\",\n      x.day,\n      max(x.date)as \"time\"\nFROM (\nSELECT\n  sum(calories) as \"calories\",\n  date,\nmax(day) as \"day\"\nFROM\n  meals\nWHERE\n  $__timeFilter(date)\nGROUP BY date\n)x\nGROUP BY day\nORDER BY CASE\n             WHEN day = '''Monday''' THEN 1\n             WHEN day = '''Tuesday''' THEN 2\n             WHEN day = '''Wednesday''' THEN 3\n             WHEN day = '''Thursday''' THEN 4\n             WHEN day = '''Friday''' THEN 5\n             WHEN day = '''Saturday''' THEN 6\n             WHEN day = '''Sunday''' THEN 7\n             END ASC;\n"
    }
   ]
  }
 ]
}